### PR TITLE
Allow quoting of first idea post

### PR DESCRIPTION
**Pull request by VSEphpbb**
@CHItA I think said you can't quote the first post in an idea. I guess this was intentional as the first post is made by an Ideas Bot (though I have no idea why that is the case).

Anyway this PR will allow quoting of the first idea post, but adds a bit of overhead (about 5 additional SQL queries) due to all the work needed to find the original post author's username within the posting.php codebase.

So I'm not sure this is worth having.

### CODE REVIEW

**Comment by DavidIQ** [comment]
Or was it @Elsensee

**Comment by Elsensee** [comment]
Hey, don't drag me into this, that was definitely @CHItA's idea! ;)

But if you ask for my opinion: I don't see any reason for this.

**Comment by CHItA** [comment]
I don't really care that much. I can stick to copy-pasting for now, just expect me to bitch about it every now and then. :)

**Comment by DavidIQ** [comment]
@CHItA Is your thoughts on quoting just for dissecting the idea and responding to different parts?

**Pull request closed without merging**
