### PR TITLE
Use CSS-based thumbs-up/down ratings

### LINKED ISSUE #112: Replace thumbs up/down green/red images with CSS
Right now it's an image being used as a background. It's already a div so it can be properly styled through a CSS class. Can use these from Font Awesome for the thumbs:

https://fontawesome.com/v4.7.0/icon/thumbs-o-up
https://fontawesome.com/v4.7.0/icon/thumbs-o-down

### PR DESCRIPTION
**Pull request by VSEphpbb**
Closes #112

CSS based (with FontAwesome) button and thumbs up/down. A little orange check mark is shown if you already voted on the badge that reflects your vote. Also title will show on hover saying if you already voted for/against the idea.

Screen Shot 2020-05-07 at 11 12 02 PM

And in a topic. The check mark will update on the fly if you change your vote or remove your vote.
Screen Shot 2020-05-07 at 11 11 47 PM

### CODE REVIEW

**Comment by VSEphpbb** [comment]
This PR also fixes a bug I found in the voting system:
If you open an idea that you already voted in, for example you thumbs-upped, then you remove your vote, then you try to put your up-vote back, it will instead count as a down-vote.

**Comment by VSEphpbb** [comment]
Here's an animation of it working, with the check marks for the user too.
Untitled

**Comment by VSEphpbb** [comment]
Updated button colors
Screen Shot 2020-05-08 at 11 22 47 AM

**Comment by VSEphpbb** [comment]
Also just added Ajax loading spinner/inidicators. I've been doing so much test voting I realized the lack of them sucks. Now all ajax ops have a spinner during their operations.

**Comment by Dode123** [comment]
> Updated button colors
> Screen Shot 2020-05-08 at 11 22 47 AM

Looks very good @VSEphpbb :)

**Comment by VSEphpbb** [comment]
Updated animation of it in action
Untitled

**Pull request merged**
